[project]
name = "healthcare-records-blockchain"
requirements = []
cache_dir = ".cache"
telemetry = false

[contracts.healthcare-records]
path = "contracts/healthcare-records.clar"
depends_on = ["healthcare-audit"]

[contracts.healthcare-audit]
path = "contracts/healthcare-audit.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = true
trusted_sender = false
trusted_caller = false
callee_filter = true
